name: Count Lines of Code

on:
  schedule:
    #- cron: '0 10 * * 1,4'  # every 30 minutes
  workflow_dispatch:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install cloc
        run: sudo apt-get install -y cloc

      - name: Count lines
        run: cloc . --exclude-dir=.github,.git > loc.txt

      - name: Commit LOC report
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add loc.txt
          git commit -m "Update LOC report"
          git push || echo "No changes to commit"
