name: Count Lines of Code Across All Repos

on:
  schedule:
    # - cron: '0 10 * * 1,4'  # 10:00 AM every Monday and Thursday
  workflow_dispatch:

jobs:
  count-loc:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current repo to commit the final result
      - uses: actions/checkout@v3

      # Set up GitHub authentication
      - name: Set up GitHub Authentication
        run: |
          echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      # Install necessary tools
      - name: Install Git and cloc
        run: |
          sudo apt-get update
          sudo apt-get install -y git cloc jq

      # Get list of all repos you own
      - name: Get list of repositories
        id: repos
        run: |
          set -x  # Enable command echoing for debugging
          curl -H "Authorization: token $GH_TOKEN" \
               "https://api.github.com/user/repos?per_page=100" \
               | jq -r '.[].full_name' > repos.txt
          
      # Debug: Print the list of repositories
      - name: Print repo list for debugging
        run: |
          cat repos.txt

      # Clone, count lines of code, and aggregate results
      - name: Count lines across all repos
        run: |
          set -x  # Enable command echoing for debugging
          total_lines=0
          for repo in $(cat repos.txt); do
            echo "Cloning $repo..."
            git clone https://$GH_TOKEN@github.com/$repo.git
            cd $(basename "$repo")
            # Run cloc on the repo
            lines=$(cloc . --exclude-dir=.github,.git --json | jq '.SUM.code')
            total_lines=$((total_lines + lines))
            cd ..
            rm -rf $(basename "$repo")
          done
          echo "Total lines of code: $total_lines" > loc.txt

      # Commit the result (loc.txt) back to the current repository
      - name: Commit LOC report
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add loc.txt
          git commit -m "Auto-update LOC report - $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "Nothing to commit"
          git remote set-url origin https://$GH_TOKEN@github.com/${{ github.repository }}.git
          git push
